// Generated by https://quicktype.io

class AddUserMaenResponse {
  String? id;
  String? username;
  String? email;
  String? name;
  String? role;
  String? createdAt;
  String? token;

  AddUserMaenResponse({
    this.id,
    this.username,
    this.email,
    this.name,
    this.role,
    this.createdAt,
    this.token,
  });
}
