// Generated by https://quicktype.io

class LoginResponse {
  String? id;
  String? username;
  String? email;
  String? name;
  String? role;
  String? createdAt;
  String? token;

  LoginResponse({
    this.id,
    this.username,
    this.email,
    this.name,
    this.role,
    this.createdAt,
    this.token,
  });
  LoginResponse.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    username = json['username'];
    email = json['email'];
    role = json['role'];
    createdAt = json['createdAt'];
    token = json['token'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['username'] = this.username;
    data['email'] = this.email;
    data['role'] = this.role;
    data['createdAt'] = this.createdAt;
    data['token'] = this.token;
    return data;
  }
}
