// Generated by https://quicktype.io

class AddUserMaenDto {
  String? username;
  String? password;
  String? verifyPassword;
  String? email;
  String? name;
  int? numMemberOfFamily;
  double? salary;

  AddUserMaenDto({
    this.username,
    this.password,
    this.verifyPassword,
    this.email,
    this.name,
    this.numMemberOfFamily,
    this.salary,
  });
  AddUserMaenDto.fromJson(Map<String, dynamic> json) {
    username = json['username'];
    password = json['password'];
    verifyPassword = json['verifyPassword'];
    email = json['email'];
    name = json['name'];
    numMemberOfFamily = json['numMemberOfFamily'];
    salary = json['salary'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['username'] = this.username;
    data['password'] = this.password;
    data['verifyPassword'] = this.verifyPassword;
    data['email'] = this.email;
    data['name'] = this.name;
    data['numMemberOfFamily'] = this.numMemberOfFamily;
    data['salary'] = this.salary;
    return data;
  }
}
